name: Generate a pdf highlighting differences from the base commit

run-name: Diff build pipeline triggered by ${{ github.actor }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Compile-Linux-GNU:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate a diff file (main text)
        uses: egor-demidov/create-latexdiff@v1.1
      - name: Archive compiled artifact
        uses: actions/upload-artifact@v3
        with:
          name: diff-file-main
          path: |
            diff.pdf
      - name: Generate a diff file (SI)
        uses: egor-demidov/create-latexdiff@v1.1
        with:
          main-file: 'supplemental.tex'
      - uses: actions/upload-artifact@v3
        with:
          name: diff-file-si
          path: |
            diff.pdf
