name: Generate a pdf highlighting differences from the base commit

run-name: Diff build pipeline triggered by ${{ github.actor }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Compile-Linux-GNU:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install texlive
        run: |
          sudo apt install texlive-full
      - name: Install the LatexMk configuration
        run: |
          cp home/.latexmkrc ~/.latexmkrc
      - name: Compile the initial version
        run: |
          unzip optics-paper-3644567e603ba3640b18f1cd82b42f9f48da5199.zip
          cd optics-paper-3644567e603ba3640b18f1cd82b42f9f48da5199
          latexmk -pdf -interaction=nonstopmode main.tex
      - name: Compile the current version
        run: |
          latexmk -pdf -interaction=nonstopmode main.tex
      - name: Generate and compile a diff file
        run: |
          latexdiff --flatten optics-paper-3644567e603ba3640b18f1cd82b42f9f48da5199/main.tex main.tex > diff.tex
          latexmk -pdf -interaction=nonstopmode diff.tex
      - name: Archive compiled artifact
        uses: actions/upload-artifact@v3
        with:
          name: diff-file
          path: |
            diff.pdf
