name: Generate a pdf highlighting differences from the base commit

run-name: Diff build pipeline triggered by ${{ github.actor }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Compile-Linux-GNU:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install texlive
        run: |
          sudo apt install texlive-full
      - name: Install the LatexMk configuration
        run: |
          cp home/.latexmkrc ~/.latexmkrc
      - name: Compile the initial version
        run: |
          unzip optics-paper-3644567e603ba3640b18f1cd82b42f9f48da5199.zip
          cd optics-paper-3644567e603ba3640b18f1cd82b42f9f48da5199
          latexmk -pdf -interaction=nonstopmode main.tex
      - name: Compile the current version
        run: |
          echo "Current directory: $(pwd)"
      - name: Build
        run: |
          mkdir dist/soot-dem/bin
          mkdir cmake-build
          cd cmake-build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
          strip aggregate_deposition
          strip afm_necking_fraction
          strip restructuring
          mv ./aggregate_deposition ../dist/soot-dem/bin/
          mv ./afm_necking_fraction ../dist/soot-dem/bin/
          mv ./restructuring ../dist/soot-dem/bin/
      - name: Archive compiled artifact
        uses: actions/upload-artifact@v3
        with:
          name: soot-dem-linux-gnu-x86_64
          path: |
            dist
